config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/about' => 'home#about'

  patch '/activate_user/:id' => 'activations#update', as: :user_activation

  delete '/activate_user/:id' => 'activations#delete'

  get '/activate_users' => 'activations#index'

  get "users/autocomplete" => "users#autocomplete"

  resources :users do
   resources :profiles do
      resources :experiences
      resources :projects
      resources :educations
      resources :skills
      resources :descriptions
    end
  end
  resources :contact_forms, only: [:new, :create]

  resources :search do
    get "/advanced" => "search#advanced_form", on: :collection
    post "/advanced" => "search#advanced_search", on: :collection
  end

  resources :sessions, only: [:create, :new, :destroy] do
    delete :destroy, on: :collection
  end


  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :contact_forms, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Profile do |p|
      p.user == user
    end

    # Define abilities for the passed in user here. For example:

      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/description.rb
class Description < ActiveRecord::Base
  # This is an empty model. It caused issues so we placed the description
  # as a column in the profile model instead.
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :profile

  validates :school, presence: true
  validates :major, presence: true

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :profile

  validates :company, presence: true
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :start, presence: true
  validates :end, presence: true

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :experiences, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :skills, dependent: :destroy
  mount_uploader :resume, ResumeUploader

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :profile

  validates :name, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :image_cache

  has_secure_password
  has_one :profile

  EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: EMAIL_REGEX

  mount_uploader :image, ImageUploader

  def full_name
    "#{first_name} #{last_name}"
  end

  def default_image
      @image = '/images/default-cat.jpg'
  end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @sign_up_url = new_user_path
    @for_hire_url = users_path + '/?hire?=true'
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
    @profile.user = User.find params[:user_id]
  end

  def create
    @profile = Profile.new profile_params
    @profile.user = User.find params[:user_id]

    if @profile.save
      redirect_to user_profile_path(@profile.user, @profile), notice: "Updated Project"
    else
      render :new
    end
  end

  def show
    @profile = Profile.find params[:id]
  end

  def edit
    @profile = Profile.find params[:id]
  end

  def update
    @profile = Profile.find params[:id]
    if @profile.update profile_params
      redirect_to user_profile_path(@profile.user, @profile)
    else
      render :edit
    end
  end

  private

  def profile_params

    params.require(:profile).permit(:twitter, :github, :linkedin, :resume, :description)

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :index, :autocomplete]
  before_action :current_user, only: [:edit, :update, :destroy]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @profile = Profile.new
    @profile.user = @user
    @user.profile = @profile
    if @user.save && @profile.save
      ActivationsMailer.activation_notification_admin(@user).deliver_later
      session[:user_id] = @user.id
      redirect_to new_user_profile_path(@user), notice: "Logged In!"
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
    redirect_to user_profile_path(@user, @user.profile)
  end

  def index
    @admin = User.where(User.arel_table[:admin].eq(true))
    if params[:hire?]
      @header = "Students for Hire"
      @page = params[:page].to_i
      @users = User.where(for_hire: true).order(created_at: :desc).page(@page).per(10)
    else
      @header = "All Students"
      @page = params[:page].to_i
      @users = User.order(created_at: :desc).page(@page).per(10)
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to root_path
    else
      render :edit
    end
  end

#   def autocomplete
#   users = User.all.map do |user|
#     {
#       name: user.first_name,
#       email: user.email
#     }
#   end
#
#   render json: users
# end

  private

  def find_user
    @user = User.find(session[:user_id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :for_hire, :image)
  end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/profiles/_form.html.erb
<div class = 'well bs-component'>
  <legend>New User</legend>
    <%= simple_form_for [@profile.user, @profile] do |f| %>
      <%= f.input :twitter, placeholder: "https://twitter.com/taylorswift13" %>
      <%= f.input :linkedin, placeholder: "https://www.linkedin.com/in/rbranson" %>
      <%= f.input :github, placeholder: "https://github.com/tkbeili" %>
      <%= f.input :resume, multiple: true %>
      <%= f.input :description %>
      <%= f.button :submit, class: "btn-primary" %>
    <% end %>
</div>

app/views/profiles/_form2.html.erb
<div class = 'well bs-component'>
  <legend>Edit User</legend>
    <%= simple_form_for [@profile.user, @profile] do |f| %>
      <%= f.input :twitter %>
      <%= f.input :linkedin %>
      <%= f.input :github %>
      <%= f.input :resume, multiple: true %>
      <%= f.input :description %>
      <%= f.button :submit, class: "btn-primary" %>
    <% end %>
</div>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>
<%= render "profiles/form2" %>

app/views/profiles/new.html.erb
<h1>Add Profile Info</h1>
<%= render "profiles/form" %>

app/views/profiles/show.html.erb
<!-- Prof Pic -->
<div class="flexbox">
  <div id="profile-picture">
    <% if @profile.user.image.file.nil? %>
    <%= image_tag("default_profile_picture.png") %>
    <% else %>
    <%= image_tag(@profile.user.image.url(:medium)) %>
    <% end %>
  </div>
  <div style="display: inline-block">
    <h1><%= @profile.user.full_name %></h1>
    <div style="display: inline-block; margin-left: 10px; bottom: 20px;">
      <%= link_to fa_icon("linkedin"), "#{@profile.linkedin}" %>
      <%= link_to fa_icon("twitter"), "#{@profile.twitter}" %>
      <%= link_to fa_icon("github"), "#{@profile.github}" %>
      <%= link_to fa_icon("download"), @profile.resume.url %>
    </div>
    <div id="description-form">
      <%= @profile.description %>
    </div>
  </div>
</div>



<%= link_to "Contact", new_contact_form_path(id: @profile.user.id), class: "btn btn-primary" %>

<div id=<%= dom_id(@profile.user) %>>
  <% if can? :manage, @profile.user %>
    <%= render "activations/form", user: @profile.user %>
  <% end %>
</div>

<ul class="nav nav-tabs">
  <li class="active"><a href="#skills" data-toggle="tab" aria-expanded="false"><h4>Skills</h4></a></li>
  <li class=""><a href="#projects" data-toggle="tab" aria-expanded="false"><h4>Projects</h4></a></li>
  <li class=""><a href="#education" data-toggle="tab" aria-expanded="false"><h4>Education</h4></a></li>
  <li class=""><a href="#experiences" data-toggle="tab" aria-expanded="false"><h4>Experiences</h4></a></li>
</ul>

<div id="myTabContent" class="tab-content">

  <div class="tab-pane fade in active" id="skills">
    <div>
      <% if can? :manage, @profile %>
        <%= link_to "Add Skills", new_user_profile_skill_path(@profile.user, @profile), remote: :true %>
      <% end %>
      <div id="skill-form"></div>
    </div>
    <div id="list">
      <%= render "skills/list", {skills: @profile.skills, profile: @profile}%>
    </div>
  </div>

  <div class="tab-pane fade" id="projects">
    <div>
      <% if can? :manage, @profile %>
        <%= link_to "Add Projects", new_user_profile_project_path(@profile.user, @profile), remote: :true%>
      <% end %>
      <div id="project-form"></div>
    </div>
    <div id="list">
      <%= render "projects/list", {skills: @profile.skills, profile: @profile}%>
    </div>
  </div>

  <div class="tab-pane fade" id="education">
    <div>
      <% if can? :manage, @profile %>
        <%= link_to "Add Educations", new_user_profile_education_path(@profile.user, @profile), remote: :true%>
      <% end %>
      <div id="education-form"></div>
    </div>
    <div id="list">
      <%= render "educations/list", {skills: @profile.skills, profile: @profile}%>
    </div>
  </div>

  <div class="tab-pane fade" id="experiences">
    <div>
      <% if can? :manage, @profile %>
        <%= link_to "Add Experiences", new_user_profile_experience_path(@profile.user, @profile), remote: :true%>
      <% end %>
      <div id="experience-form"></div>
    </div>
    <div id="list">
      <%= render "experiences/list", {skills: @profile.skills, profile: @profile}%>
    </div>
  </div>

</div>