config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/about' => 'home#about'

  patch '/activate_user/:id' => 'activations#update', as: :user_activation

  delete '/activate_user/:id' => 'activations#delete'

  get '/activate_users' => 'activations#index'

  get "users/autocomplete" => "users#autocomplete"

  resources :users do
   resources :profiles do
      resources :experiences
      resources :projects
      resources :educations
      resources :skills
      resources :descriptions
    end
  end
  resources :contact_forms, only: [:new, :create]

  resources :search do
    get "/advanced" => "search#advanced_form", on: :collection
    post "/advanced" => "search#advanced_search", on: :collection
  end

  resources :sessions, only: [:create, :new, :destroy] do
    delete :destroy, on: :collection
  end


  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :contact_forms, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Profile do |p|
      p.user == user
    end

    # Define abilities for the passed in user here. For example:

      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/description.rb
class Description < ActiveRecord::Base
  # This is an empty model. It caused issues so we placed the description
  # as a column in the profile model instead.
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :profile

  validates :school, presence: true
  validates :major, presence: true

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :profile

  validates :company, presence: true
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :start, presence: true
  validates :end, presence: true

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :experiences, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :skills, dependent: :destroy
  mount_uploader :resume, ResumeUploader

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :profile

  validates :name, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :image_cache

  has_secure_password
  has_one :profile

  EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: EMAIL_REGEX

  mount_uploader :image, ImageUploader

  def full_name
    "#{first_name} #{last_name}"
  end

  def default_image
      @image = '/images/default-cat.jpg'
  end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @sign_up_url = new_user_path
    @for_hire_url = users_path + '/?hire?=true'
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_user, except: [:index]
  before_action :find_profile
  before_action :find_skill, only: [:edit, :update, :destroy]
  def new
    @skill = Skill.new
    respond_to do |format|
      format.html { render "skills/new" }
      format.js   { render "skills/create_success" }
    end
  end


  def create
    @skill = Skill.new skill_params
    @skill.profile = @profile
    if @skill.save
      redirect_to user_profile_path(@user, @profile),notice:  "New Skill Created!"
    else
      flash[:alert] = "Error. Skill not created!"
      redirect_to user_profile_path(@user, @profile)
    end
  end



  def index
    @skills = Skill.all
    respond_to do |format|
      format.html { render "skills/index"}
      format.js   { render "skills/display"}
    end
  end

  def edit
    redirect_to root_path, alert: "access defined" unless can? :edit, @profile
    respond_to do |format|
      format.html { render }
      format.js   { render :update_success }
    end
  end


  def update
    redirect_to root_path, alert: "access defined" unless can? :update, @profile
    if @skill.update skill_params
      redirect_to user_profile_path(@user, @profile)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path, alert: "access defined" unless can? :destroy, @profile
    @skill.destroy
    redirect_to user_profile_path(@user,@profile)
  end


  private

  def skill_params
    skill_params = params.require(:skill).permit(:name, :rating)
  end

  def find_skill
    @skill = Skill.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :index, :autocomplete]
  before_action :current_user, only: [:edit, :update, :destroy]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @profile = Profile.new
    @profile.user = @user
    @user.profile = @profile
    if @user.save && @profile.save
      ActivationsMailer.activation_notification_admin(@user).deliver_later
      session[:user_id] = @user.id
      redirect_to new_user_profile_path(@user), notice: "Logged In!"
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
    redirect_to user_profile_path(@user, @user.profile)
  end

  def index
    @admin = User.where(User.arel_table[:admin].eq(true))
    if params[:hire?]
      @header = "Students for Hire"
      @page = params[:page].to_i
      @users = User.where(for_hire: true).order(created_at: :desc).page(@page).per(10)
    else
      @header = "All Students"
      @page = params[:page].to_i
      @users = User.order(created_at: :desc).page(@page).per(10)
    end
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to root_path
    else
      render :edit
    end
  end

#   def autocomplete
#   users = User.all.map do |user|
#     {
#       name: user.first_name,
#       email: user.email
#     }
#   end
#
#   render json: users
# end

  private

  def find_user
    @user = User.find(session[:user_id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :for_hire, :image)
  end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/skills/_form.html.erb
<div class = 'well bs-component'>
  <legend>Edit Skill</legend>
  <% @skill.errors.full_messages.join(", ") %>
<%= simple_form_for [@user, @profile, @skill] do |f| %>
  <%= f.input :name %>
  <%= f.input :rating, collection: 1..10%>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>
</div>

app/views/skills/_form2.html.erb
<div class = 'well bs-component'>
  <legend>Add Skill</legend>
  <% @skill.errors.full_messages.join(", ") %>
<%= simple_form_for [@user, @profile, @skill] do |f| %>
  <%= f.input :name %>
  <%= f.input :rating, collection: 1..10%>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/skills/_list.html.erb
<% profile.skills.each do |skill| %>
  <div>
    <h4 style="display: inline-block"><%= skill.name %></h4>
    <h5 style="display: inline-block">(<%= skill.rating %> / 10)</h5>
    <% if can? :manage, profile %>
      <%= link_to "Edit", edit_user_profile_skill_path(profile.user, profile, skill), remote: :true %>
      <%= link_to "Delete", user_profile_skill_path(profile.user, profile, skill), method: :delete, data:  {confirm: "Are you sure?" } %>
    <div id="skill-edit-form"></div>
    <% end %>
    <div class="progress progress-striped active">
      <div class="progress-bar" style="width: <%= skill.rating %>0%"></div>
    </div>
  </div>
<% end %>
<hr>

app/views/skills/create_failure.js.erb
$("#skill-form").html("")

app/views/skills/create_success.js.erb
console.log("add skill")
// $('#list').prepend("<%#= j(render('/skills/list', {skill: @skill})) %>");

<% @skill = Skill.new %>
$('#skill-form').html('<%= j render "form" %>')

app/views/skills/display.js.erb
console.log("skills")
$('#list').html("<%= j render 'skills/list', profile: @profile %>")

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render "form" %>

app/views/skills/index.html.erb
<h1>All Skills</h1>
<%= link_to "Add new skill", new_skill_path %>

<% @skills.each do |skill|  %>
  <div>
    <h2><%= skill.name %></h2>
    <p><%= skill.rating %></p>
    <%= link_to "Edit", edit_skill_path(skill) %>
    <%= link_to "Delete", skills_path, method: :delete, data: {confirm: "Are  you sure?"} %>
    <hr>
  </div>
<% end %>

app/views/skills/new.html.erb
<h1> New Skill </h1>

<%= render "form2" %>

app/views/skills/update_success.js.erb
<% @skill = Skill.find params[:id]%>
$('#skill-edit-form').html('<%= j render "form" %>')