config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/about' => 'home#about'

  patch '/activate_user/:id' => 'activations#update', as: :user_activation

  delete '/activate_user/:id' => 'activations#delete'

  get '/activate_users' => 'activations#index'

  get "users/autocomplete" => "users#autocomplete"

  resources :users do
   resources :profiles do
      resources :experiences
      resources :projects
      resources :educations
      resources :skills
      resources :descriptions
    end
  end
  resources :contact_forms, only: [:new, :create]

  resources :search do
    get "/advanced" => "search#advanced_form", on: :collection
    post "/advanced" => "search#advanced_search", on: :collection
  end

  resources :sessions, only: [:create, :new, :destroy] do
    delete :destroy, on: :collection
  end


  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :contact_forms, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Profile do |p|
      p.user == user
    end

    # Define abilities for the passed in user here. For example:

      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/description.rb
class Description < ActiveRecord::Base
  # This is an empty model. It caused issues so we placed the description
  # as a column in the profile model instead.
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :profile

  validates :school, presence: true
  validates :major, presence: true

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :profile

  validates :company, presence: true
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :start, presence: true
  validates :end, presence: true

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :experiences, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :skills, dependent: :destroy
  mount_uploader :resume, ResumeUploader

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :profile

  validates :name, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :image_cache

  has_secure_password
  has_one :profile

  EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: EMAIL_REGEX

  mount_uploader :image, ImageUploader

  def full_name
    "#{first_name} #{last_name}"
  end

  def default_image
      @image = '/images/default-cat.jpg'
  end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @sign_up_url = new_user_path
    @for_hire_url = users_path + '/?hire?=true'
  end

end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="foot">
  <div class="container-fluid">
    <%= link_to ("Home"), root_path %>
    |
    <a href="http://codecore.ca/">CodeCore Bootcamp</a>
    |
    <%= link_to "About", home_about_path %>

    <p>142 W Hastings St. // Vancouver, BC // Canada // (604) 559-CODE (2633) </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("codecore_for_hire.png"), root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Recruit<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "All Students", users_path%></li>
            <li><%= link_to "Students for Hire", users_path(hire?: true)%></li>
            <li><%= link_to "Advanced Search", advanced_search_index_path%></li>
          </ul>
        </li>
      </ul>

      <%= form_tag("/search", method: "get", enforce_utf8: false, class: "navbar-form navbar-right") do %>
      <%= text_field_tag :query, nil, class: "form-control", placeholder: 'Search' %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        <%= fa_icon("search") %>
      <% end %>
      <% end %>



      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hello, <%=current_user.first_name%><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% if current_user.profile %>
                  <li><%= link_to "My Profile", user_profile_path(current_user, current_user.profile)%></li>
                  <li><%= link_to "Edit Profile", edit_user_profile_path(current_user, current_user.profile)%></li>
                  <li><%= link_to "Edit Account", edit_user_path(current_user)%></li>
                  <% if current_user.admin? %>
                    <li><%= link_to "Activate Users", activate_users_path %></li>
                  <% end %>
                <% end %>
              </ul>
            </li>
            <li><%= link_to "Sign Out", session_path(current_user), method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", "#loginModal", "data-toggle" => "modal"%></li>
          <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codecode For Hire</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <% if flash[:notice] %>
      <div id= "flash" class="alert alert-dismissible alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div id= "flash" class="alert alert-dismissible alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
    <%= render "sessions/form"%>
    <%= render "users/form" %>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>